server:
  shutdown: graceful

spring:
  application:
    name: spring-webflux-java

logging:
  level:
    org.springframework.r2dbc: debug

jwt:
  access-token:
    key: S3fR9pOWh0D2k-MX37rm8N6K3u0aXvdcqD4muOxZK8g
    expiration: 10m
  refresh-token:
    key: XhNd_6u1OJvYOCp2JZ0cwlQUKtIJ6B5wAxXHfPSmeTA
    expiration: 7d

crypto:
  secret-key: d9ANIqIyfTygI92m6jWFfAzUbEP73TNB
  iv-parameter: F22DBBB19D308662

cors:
  allowed-origins:
    - "http://localhost:3000"
  allowed-methods:
    - "HEAD"
    - "GET"
    - "POST"
    - "PUT"
    - "DELETE"
  allowed-headers:
    - "*"

management:
  endpoints:
    web:
      exposure:
        include: "*"
